[workspace]
resolver = "2"
members = ["contract", "api"]

[workspace.dependencies]
# Centralizing dependencies helps keep versions consistent across the workspace
soroban-sdk = "25.0.0"

[profile.release]
opt-level = "z"          # Optimize for size (critical for WASM contracts)
overflow-checks = true   # Safety requirement for Stellar
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true
